services:
  # Servicio de la Base de Datos (MySQL)
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: sistema_inventario
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      # Mapea el puerto 3306 del contenedor al 3306 de tu máquina
      - "3308:3306"
    volumes:
      # Volumen para persistir los datos de la base de datos
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "admin", "-padmin123"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Servicio del Backend (API)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_api
    restart: always
    ports:
      # Mapea el puerto 4000 del contenedor al 4000 de tu máquina
      - "4001:4000"
    environment:
      PORT: 4001
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: sistema_inventario
      DB_PORT: 3306
    volumes:
      # Monta la carpeta de uploads para que los archivos persistan
      - ./src/backend/uploads:/app/src/backend/uploads
    depends_on:
      db:
        # Espera a que la base de datos esté lista antes de iniciar el backend
        condition: service_healthy

  # Servicio del Frontend (React App)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        # Pasa la URL del API como argumento de build
        VITE_API_URL: http://192.168.18.200:4001
    container_name: frontend_app
    restart: always
    ports:
      # Mapea el puerto 80 del contenedor al 8080 de tu máquina
      - "9090:80"
    depends_on:
      # Asegura que el servicio 'backend' se inicie antes que el 'frontend'
      - backend

volumes:
  # Declara el volumen para la base de datos
  mysql-data:
